sass:
    sass_dir: _sass
    style: :compressed

gems:
    - jekyll-github-metadata

defaults:
    -
        scope:
            path: "pages" # an empty string here means all files in the project
        values:
            layout: "default"
            navigation_weight: 0 # for navigation
            comments: false # for parliamone
